baseURL = "https://coruscate.xyz"
languageCode = "en-gb"
defaultContentLanguage = "en"
title = "C o r u s c a t e"
theme = "cupper-hugo-theme"
googleAnalytics = ""
disqusShortname = ""
enableGitInfo = true

enableRobotsTXT = true
disableAliases = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "This description is out of date."
  homeMetaContent = "A personal blog."
  footer = "&copy; 2019 Pedro Figueiredo"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = ""
  katex = true
  disallow_search_engines = false

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 1
  [[menu.nav]]
    name = "Sketches"
    url = "https://soundcloud.com/everythingdies"
    weight = 2
  [[menu.nav]]
    name = "Releases"
    url = "https://straywool.bandcamp.com"
    weight = 3
  [[menu.nav]]
    name = "Playlist"
    url = "https://buymusic.club/list/pedro-figueiredo-lofi-ambient"
    weight = 4
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 6

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    enableDNT = true
    simple = true
  [privacy.vimeo]
    simple = true
  [privacy.youtube]
    privacyEnhanced = true

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
