baseURL = "https://coruscate.xyz/"
languageCode = "en-gb"
title = "c o r u s c a t e"
theme = "minimal"

[params]
    author = "Pedro Figueiredo"
    description = "This description is out of date."
    githubUsername = "pfig"
    accent = "#FA5858"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-light"
    highlightLanguages = ["go", "haskell", "python", "clojure"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Writing"
    weight = 3

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

#[[menu.icon]]
#    url = "https://github.com/pfig/"
#    name = "github"
#    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/pfig/"
#    name = "twitter"
#    weight = 3

[[menu.icon]]
    url = "https://instagram.com/pfig/"
    name = "instagram"
    weight = 5
