baseURL = "https://coruscate.xyz"
languageCode = "en-gb"
defaultContentLanguage = "en"
title = "C o r u s c a t e"
theme = "cupper-hugo-theme"
googleAnalytics = ""
disqusShortname = ""
enableGitInfo = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "This description is out of date."
  homeMetaContent = "A personal blog."
  footer = "&copy; 2019 Pedro Figueiredo"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = ""
  katex = true

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    enableDNT = true
    simple = true
  [privacy.vimeo]
    simple = true
  [privacy.youtube]
    privacyEnhanced = true
